### ISSUE TITLE
Value Error: Attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by michaelikechi** [NREL/Marmot#17]
Throws an error when plotting generation stack for regions with empty sequence 

![Picture1](https://user-images.githubusercontent.com/46036265/139695063-81f56908-e82b-4202-9843-23254a080a2c.jpg)

**Comment by daniellevie** [comment]
Fixed applied in commit cbb5e8b290405132f1d8ece321cd20279cf426a3
