### ISSUE TITLE
How to get correct hdf5 group names from egret_properties.csv

### ISSUE THREAD

**Issue by franzman1** [NREL/Marmot#20]
Last week when we met, we discussed creating a separate egret_properties.csv file.

The MarmotFormat class seems to use the row["data_set"] column of the properties csv file to control what the process methods are processing:
https://github.com/NREL/Marmot/blob/origin/multi_model_generalization%2Fegret/marmot/marmot_h5_formatter.py#L1652-L1655

and to name the hdf5 groups:
https://github.com/NREL/Marmot/blob/origin/multi_model_generalization%2Fegret/marmot/marmot_h5_formatter.py#L1703-L1706

So if I create an egret_properties.csv and change the names in the data_set column, this would also change the names of the hdf5 groups, which I think would cause issues for the plotting code? 

I'm not sure if there is a way around this without changing something in the MarmotFormat class. I could also just stick with the plexos_properties.csv and handle each of the PLEXOS data_set options within the EGRET process methods.

Let me know if you have any ideas or if I am misunderstanding something. Thanks!

**Comment by daniellevie** [comment]
I think we may require a master mapping file which maps each model specific row["data_set"] to a common Marmot name. A json formatted file may work well. Some properties may not have an exact mapping but we can start with the ones that do.
This might also give us more flexibility on what we name each group as well

For now we can use the current PLEXOS data_set names as the common Marmot ones.

What do you think?

**Comment by franzman1** [comment]
Okay, that sounds good! So that mapping file would be used in the second set of lines I linked above?

**Comment by daniellevie** [comment]
> Okay, that sounds good! So that mapping file would be used in the second set of lines I linked above?

Yes I think that's the only place it will be needed. Since the data is saved within a method, you should only need to include the mapping file here. This method will also need to receive the **sim_model** variable to know which mapping to use (i.e PLEXOS or EGRET)
https://github.com/NREL/Marmot/blob/527915a557a1fcf8303b5d3e484625fe1f53d427/marmot/marmot_h5_formatter.py#L1543

**Comment by franzman1** [comment]
Hi Daniel,

I'm able to run the marmot_h5_formatter.py with the EGRET option without running into an error, but when I check the outputted h5 file, it seems to be empty. When I try with the PLEXOS option it also seems to be empty except for some metadata. I am a bit stuck on why this is happening, so I was wondering if you might know?

I pushed the current state of codes that I have to origin/multi_model_generalization/egret. 

Thanks!

**Comment by daniellevie** [comment]
Looks like you hadn't defined the variable dateset correctly. I have pushed a small change to your branch. See if it works now 

See the diff below for the code change 
https://github.com/NREL/Marmot/commit/abe51fe6620ba4c2404a143300c46d2beca512a2#diff-02c29e1533e2388564ab1a7b616609f3aaecf56a21148130ae5b681307243811R1751

Also I'm seeing other warnings in some of the egret functions, timestamp is not defined 
![image](https://user-images.githubusercontent.com/43964549/152262859-409f1c77-299c-479d-9093-7d009a224843.png)

**Comment by franzman1** [comment]
Great, thank you for catching that! 

I am trying to test the formatted h5 file for EGRET with the marmot_plot_main.py script and I am running into a metadata key error:

Traceback (most recent call last):
  File "marmot_plot_main.py", line 782, in <module>
    main()
  File "marmot_plot_main.py", line 778, in main
    initiate.run_plotter()
  File "marmot_plot_main.py", line 456, in run_plotter
    zones = pd.concat([meta.zones(scenario) for scenario in self.Scenarios])
  File "marmot_plot_main.py", line 456, in <listcomp>
    zones = pd.concat([meta.zones(scenario) for scenario in self.Scenarios])
  File "/g/g16/franzman/NAERM_CD_project/Marmot/marmot/meta_data.py", line 379, in zones
    self._read_data(filename)
  File "/g/g16/franzman/NAERM_CD_project/Marmot/marmot/meta_data.py", line 93, in _read_data
    partitions = [key for key in self.h5_data['metadata'].keys()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/g/g16/franzman/NAERM_CD_project/marmot_env/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'metadata' doesn't exist)"

I did not write an output_metadata method for EGRET, so I think the default Process output_metadata method is being used. Should I be defining a specific output_metadata method for EGRET?

Thank you!

**Comment by daniellevie** [comment]
I forgot about the metadata in the plotter..
Right now you may just want to comment out all the code from lines 454 to 536. This piece is basically getting the unique regions and zones from the h5 file which are used later to plot, this is then saved to the **Zones** variable as a list. 

For now add your own list of regions/zones to the Zones variable and see how the rest of the test goes. 
We'll need to think of how to handle this, we need to be able to get the list of geographic areas that exist in the formatted results in this section. Is this information saved in a section of the json file which we could easily extract or create some sort of egret metadata?

**Comment by franzman1** [comment]
Okay, got it. I tried custom defining the Zones variable with a list of values and running the plotter with those lines commented out. I am running into a key error, but I'm not sure where the key error is coming from:

Traceback (most recent call last):
  File "marmot_plot_main.py", line 789, in <module>
    main()
  File "marmot_plot_main.py", line 785, in main
    initiate.run_plotter()
  File "marmot_plot_main.py", line 631, in run_plotter
    end_date_range = row.iloc[8])
  File "/g/g16/franzman/NAERM_CD_project/Marmot/marmot/plottingmodules/generation_stack.py", line 753, in gen_stack
    outputs[zone_input] = mkplot(outputs, zone_input, [self.Scenarios[0]])
  File "/g/g16/franzman/NAERM_CD_project/Marmot/marmot/plottingmodules/generation_stack.py", line 543, in mkplot
    Stacked_Gen = self.df_process_gen_inputs(Stacked_Gen)
  File "/g/g16/franzman/NAERM_CD_project/Marmot/marmot/plottingmodules/plotutils/plot_data_helper.py", line 208, in df_process_gen_inputs
    df = df.pivot(index='timestamp', columns='tech', values=0)
  File "/g/g16/franzman/NAERM_CD_project/marmot_env/lib/python3.7/site-packages/pandas/core/frame.py", line 5923, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/g/g16/franzman/NAERM_CD_project/marmot_env/lib/python3.7/site-packages/pandas/core/reshape/pivot.py", line 449, in pivot
    indexed = data._constructor_sliced(data[values].values, index=index)
  File "/g/g16/franzman/NAERM_CD_project/marmot_env/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/g/g16/franzman/NAERM_CD_project/marmot_env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The zones and regions can be extracted from the EGRET json files-- is that all the metadata would need?

**Comment by daniellevie** [comment]
It's trying to create a pivot table from the data with the values coming from column 0. This is usually the data column, i.e the only column outside of the Multiindex. Looks like you may not have named this column 0. I think it also had to be an integer and not a string so 0 instead of "0"

**Comment by franzman1** [comment]
Okay great, thank you!  I was able to get the test plot (Stacked_Gen_Facet_Grid) to work with the marmot formatted EGRET file. However, the stack graphs that are generated only have one category called "Other" and a line for demand. The EGRET tech categories are different from the PLEXOS tech categories, but I am not sure at which point I should do a mapping. Should I just map the EGRET names to PLEXOS names in the tech column in the marmot_h5_formatter.py or should things get mapped using the gen_names.csv file in marmot_plot_main.py?

**Comment by daniellevie** [comment]
Yeah all you need to do is add your generator technologies to the **gen_names.csv**. You can also create completely new mappings so no need to use the existing ones https://github.com/NREL/Marmot/blob/main/marmot/mapping_folder/gen_names.csv

If you want to set the order of your generation you can set it in **ordered_gen_categories.csv** https://github.com/NREL/Marmot/blob/main/marmot/mapping_folder/ordered_gen_categories.csv

The ordered_gen_categories _Ordered_Gen_ column are the technologies that are mapped in the gen_names.csv. The other columns in the **ordered_gen_categories.csv** can be used to plot a subset of generation, you can also add columns here to make new custom subsets. To use one of these columns enter the column name into the _TECH_SUBSET_ entry in the **user_defined_inputs.csv** 

Finally if you create new mappings, you'll also want to update the **colour_dictionary.csv** https://github.com/NREL/Marmot/blob/main/marmot/mapping_folder/colour_dictionary.csv

You can really customize this any way you like!

**Comment by daniellevie** [comment]
Also check your log files or the terminal, it will likely be printing warning messaged for you. You probably got one that said it can't map so everything will be named 'Other'

**Comment by daniellevie** [comment]
If you're interested in where the remapping happens, its here:

https://github.com/NREL/Marmot/blob/936bf319c9271164441ccb03ba944768f1bdeb1b/marmot/plottingmodules/plotutils/plot_data_helper.py#L121

**Comment by franzman1** [comment]
Thanks! I am seeing the categories in the plots now!

I am currently getting a plot for every single zone. If i want to get one plot that is aggregated over all the data, should I list all the regions in the region column and then have a second column, maybe "state", that has the same value for all rows in Regions_Zones_Mapping_Full.csv? Then if I set the AGG_BY parameter to "state", would it be aggregated to that level?

**Comment by daniellevie** [comment]
Yeah thats exactly what you would do. Just make sure you merge the self.Region_Mapping region column to the egret data. You can even make your own custom Regions_Zones_Mapping csv and replace the default in the user_defined_inputs file.

**Comment by daniellevie** [comment]
Closing this issue for now. We can open new ones when needed
