### ISSUE TITLE
Unable to open object (object 'blocks' doesn't exist) when running formatter

### ISSUE THREAD

**Issue by netr0m** [NREL/Marmot#30]
Attempting to run the Marmot formatter on an H5PLEXOS formatted file (converted from a Plexos solution ZIP using [H5PLEXOS.jl](https://github.com/NREL/H5PLEXOS.jl) leads to an error I have been unable to determine the cause of.

Tested on branches:
- main
- multi_model_generalization

Configs:
- tested with customized as well as default ones (in repository)
  - Marmot_user_defined_input.csv, plexos_properties.csv, and various mapping files.

Error:
```
#### Processing Scenario1 LT PLEXOS Results ####
Loading all HDF5 files to prepare for processing
Querying H5PLEXOS v0.6.2 file
Traceback (most recent call last):
  File "/app/Marmot/marmot/marmot_h5_formatter.py", line 1419, in <module>
    main()
  File "/app/Marmot/marmot/marmot_h5_formatter.py", line 1413, in main
    append_block_name=mconfig.parser('append_plexos_block_name'))
  File "/app/Marmot/marmot/marmot_h5_formatter.py", line 1119, in run_formatter
    files_list = process_sim_model.get_input_files()
  File "/app/Marmot/marmot/marmot_h5_formatter.py", line 251, in get_input_files
    file))
  File "/app/Marmot/marmot/h5plexos/h5plexos/query/solution.py", line 55, in __init__
    for name, dset in self.h5file["/metadata/blocks"].items():
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/conda/envs/marmot-env/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'blocks' doesn't exist)"
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '/app/Marmot/marmot/marmot_h5_formatter.py']' command failed.  (See above for error)
```

Would you happen to have any insight on what could cause this issue?

We're unsure whether this is caused by a faulty/corrupted Plexos solution file, a bug in the converter (h5plexos.jl) or formatter (marmot formatter), incorrect configurations, or something else entirely. The process has been tested using a custom Docker image based on `continuumio/miniconda3` (and `continuumio/anaconda3`).

**Comment by daniellevie** [comment]
Hi thanks for submitting this issue. 

It looks like there is something wrong with the hdf5 file after conversion with [H5PLEXOS.jl](https://github.com/NREL/H5PLEXOS.jl)

Your file appears to be missing **"/metadata/blocks"** which should be in files above v0.6.2 so yours should include it.
Are you able to open the h5file in a viewer such as HDFView? A v0.6.2 file should have a format that looks similar to this with the included blocks level. 
![image](https://user-images.githubusercontent.com/43964549/156203921-29a22137-365b-45fb-b82b-d3c6e7c01c32.png)

If you don't have a viewer you can also try accessing the file directly with h5py using the following commands:

```python
import h5py
h5file = h5py.File(path_to_your_h5filepath, "r")

# the following will show the file version
h5file.attrs.get("h5plexos")

# Check if blocks is in the metadata keys 
h5file["/metadata/"].keys()
```

I am not an active developer on [H5PLEXOS.jl](https://github.com/NREL/H5PLEXOS.jl) but I will reach out to the development team to see if we can determine the issue. 
In the mean time can you also try updating your [H5PLEXOS.jl](https://github.com/NREL/H5PLEXOS.jl) to the latest version. I believe the current version is 0.6.5. After updating you will need to re-create the h5plexos file from the original zip file.

**Comment by netr0m** [comment]
Hi @daniellevie , thanks for the quick reply!

- `/metadata/blocks` is missing. 

Indeed you're correct - the cause was from the pipeline where the H5PLEXOS conversion happens. I've raised an issue in the repository as it seems installation is consistently failing. See [NREL/H5PLEXOS.jl#9](https://github.com/NREL/H5PLEXOS.jl/issues/9)
